# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Esit\Ctoadapter\Classes\Services\Adapter\Config:

    Esit\Ctoadapter\Classes\Services\Adapter\Controller:

    Esit\Ctoadapter\Classes\Services\Adapter\Database:

    Esit\Ctoadapter\Classes\Services\Adapter\Environment:

    Esit\Ctoadapter\Classes\Services\Adapter\FilesModel:

    Esit\Ctoadapter\Classes\Services\Adapter\Idna:

    Esit\Ctoadapter\Classes\Services\Adapter\Input:

    Esit\Ctoadapter\Classes\Services\Adapter\Message:

    Esit\Ctoadapter\Classes\Services\Adapter\ModuleModel:

    Esit\Ctoadapter\Classes\Services\Adapter\PageModel:

    Esit\Ctoadapter\Classes\Services\Adapter\StringUtil:

    Esit\Ctoadapter\Classes\Services\Adapter\System:

    Esit\Ctoadapter\Classes\Services\Adapter\Validator:

